stages:
  data_split:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
    - src/stages/data_split.py
    - data/raw
    params:
    - base
    - data_split
    outs:
    - data/processed
  eval:
    cmd: python src/stages/eval.py --config=params.yaml
    deps:
    - src/stages/eval.py
    - data/processed
    - models/clf-model.joblib
    params:
    - base
    - data_split
    - train
    metrics:
    - metrics.json:
        cache: false
    plots:
    - reports/figures/cm.png:
        cache: false
