channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=23.2.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - pandas==2.0.3
  - psutil==6.1.0
  - scikit-learn==1.6.0rc1
  - scipy==1.14.1
name: mlflow-env
